import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "@/components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="w-[1366px] min-h-full m-auto ">
            <div className="px-6 py-4 ">
              <Navbar />
              <div className="p-6">{children}</div>
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
